FROM jenkins/inbound-agent
USER root
RUN mkdir /var/.virtualenvs
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    ansible
USER root
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN apt-get update
RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  bionic stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update
RUN apt-get install -y docker-ce=5:20.10.12~3-0~ubuntu-bionic
RUN usermod -aG docker jenkins
CMD ["bash"]

